AWSTemplateFormatVersion: '2010-09-09'
Description: Flatline Calling Service Infrastructure 

Resources:
  CallingServiceRoomsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Rooms
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: roomId
          AttributeType: S
        - AttributeName: recordType
          AttributeType: S
        - AttributeName: region
          AttributeType: S
      KeySchema:
        - AttributeName: roomId
          KeyType: HASH
        - AttributeName: recordType
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: region-index
          KeySchema:
            - AttributeName: region
              KeyType: HASH
            - AttributeName: recordType
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 1
