datadog.apiKey: unset

stripe.apiKey: unset
stripe.idempotencyKeyGenerator: abcdefg12345678= # base64 for creating request idempotency hash

braintree.privateKey: unset

googlePlayBilling.credentialsJson: |
  { "json": true }

appleAppStore.encodedKey: unset

directoryV2.client.userAuthenticationTokenSharedSecret: Dx9/dxgdVWPazjTqCD6nMdAwS7pnnA5GsiM+aN4pQok= # base64-encoded secret shared with CDS to generate auth tokens for Signal users
directoryV2.client.userIdTokenSharedSecret: Dx9/dxgdVWPazjTqCD6nMdAwS7pnnA5GsiM+aN4pQok= # base64-encoded secret shared with CDS to generate auth identity tokens for Signal users

svr2.userAuthenticationTokenSharedSecret: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with SVR2 to generate auth tokens for Signal users
svr2.userIdTokenSharedSecret: bbcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with SVR2 to generate auth identity tokens for Signal users

svrb.userAuthenticationTokenSharedSecret: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with SVRB to generate auth tokens for Signal users
svrb.userIdTokenSharedSecret: bbcdefghijklmnopqrstuvwxyz0123456789ABCDEFG= # base64-encoded secret shared with SVRB to generate auth identity tokens for Signal users

tus.userAuthenticationTokenSharedSecret: abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG=

gcpAttachments.rsaSigningKey: |
  -----BEGIN PRIVATE KEY-----
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  AAAAAAAA
  -----END PRIVATE KEY-----

apn.teamId: team-id
apn.keyId: key-id
apn.signingKey: |
  -----BEGIN PRIVATE KEY-----
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  AAAAAAAA
  -----END PRIVATE KEY-----

fcm.credentials: |
  { "json": true }

cdn.accessKey: test    # AWS Access Key ID
cdn.accessSecret: test # AWS Access Secret

cdn3StorageManager.clientSecret: test

unidentifiedDelivery.privateKey: KBfpvC0nnWBdxgA091zEhCEQo30N/f2ONQBsDY8mZEA=

keyTransparencyService.clientPrivateKey: |
  -----BEGIN PRIVATE KEY-----
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  ABCDEFGHIJKLMNOPQRSTUVWXYZ/0123456789+abcdefghijklmnopqrstuvwxyz
  AAAAAAAA
  -----END PRIVATE KEY-----

storageService.userAuthenticationTokenSharedSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=

zkConfig-libsignal-0.42.serverSecret: ANh8rRyDHYHFUPVG+zDo2h1J4y+SWO4KwR1zu0Sg1doACINBPcAyMBWST5EDdygA0ZTIiUnMjHlbzIehZVtlJwAiFt9uLJCEUxBCMSBgPAJdQMscQ+W1gag/2CJd2pP9CeObb5TC0l+cWjnzFMkjm9ulXo8UQ4LOzt6jIuBQmb0G0ZqFFEyal7/rwLwB/HuQc3yFv848yiLwwHoeViz6PApCnYexH8vbu/2ajy3wfxzsGX49RLoQgTOzVZzx0L9wBhpEnb1sOiqVivNAktZl1gthDZFfS1z4QYxadcKBzlwPja5yLK7wZVvwS/sXdeIljIti69rLHapEuwKOKUG8bQinCnBXjpMCuhOAm0+IHuiJ18cSvonx3jXPtuHmT1MDCgK51fKwiJcO4RksMY2NX9xgiYf2QAITLffSjPru/jRgMoq7H9g2lRsmWmg9tZLY0deP9bb/dd9DyGRBEXuZFxtBjXABWgvVyKX6qa3NbdeCxsYn+GkaV+A2eGlm7X7zBx/STFPkqfpCU6vy6o96ZX8/KqcONHS6j2qb/i3EgLMD+L1uEqX90Jur5FkKP0iECmqm5ly1IzS+o8/KeKlLW3sD3ZeoovZZguLqvRAeKvwh5H1ZuAcuY2AWMgo+K9vcBWl00BZn6rKpewPizx4E35+aRKoRhSnvNmz9+N2dPvcM6lUxutH4+FdaOmvw4zCLB2RyA+BEXtVcFYacfTMgpQWxEgEX+2gAzNrxW09wLwWUKxnbmObZTkdQ4PndLfkCCZq4yGs6x4G9ZaBXh28IdGcNfLnxa7BS33idjY91E+4NSMzY7sfdoysdhFyJOIIMB9rhuyRv8Oj2nV20YLZcyA6cayWQKBT96ZphTtMrw1451atuth13eaJuiYh66wpoZtDp12omXr33bWfcnw3tQIt/E902+BFo0Jxq4yvj1xNuQN7SjdZJ/ZCUrI/xtTRbNtvi9rCndkGA/rU4hdKxzQfqCRdGgp6MvH5M2JlX24lt7k9Yb1m94W8JuzU1sauMb7ModriRUu/fpTFmLwrfkCUBu+CaMopJZW0QKikk2SEHsXMbPzRCHFxzZ11Sc8CO1PC2C6JKdf5YV3a4Kp/prQueGCaU9BzPvguKzLBESkZ/U1bqMLY1MHJp1sirV6vBZkaZUwvPykjNHRuNRXAaTc2bbQM+tVRbYqOxsJ3fPooFjASUdHz1X+BRMR5JisoBrHTyPMn/KG+CNNJMDikKAwcnCaveZkEhX6v5bVLPWuOIqS55HCX5NTa9IbNk6oYYDVppbeOS9OhRtoUu+yYRU8Bvc3M9DHYSkLgBsUNmzHMJp1ZWy8/etYW0JCcDBbetfL6qDqr1TAc0zCtgbvfSlAy1ZcLqN7tBzXpr+RSn/i4ehGDhb+MV9nDy0pxNrenkDDg/H2rNJmgPCmBb6zWD1wL3vHsn3Ucv0I62GC6zYUB3Wkk+5x6PgpBUAcOjpcnxB9FfmLCGzqnQhRfntojgfRFpZT4DZ6tFWrk93SIMMpJvB5/yoE5YQY3cA9tm7fJHB5px9D4sTfG5xVTGblsckcTRsJOeUV31ZUBAR8/U5FgLtBmRJjVE9FJ2lG8FuA4nZVCxQgVKCngOl7Yoqu2dLCoVTs29r3/8Mkt7gycAE85DxOpcnf3nxXZNO13ZxJfyAWGNVGUVPWCs64PKu148kFpECr2JJLOJTDrNyvoXltcL2SLVP3j5cUO0uPtqljgtnfmOJ4sjGqVY2ivQzaBS2A2XA27Yv9OztGbipchsN/JgG3YatUPqTtRrUeK2+tvYA3X+FQ6wYpl/H5Iwtsm5sJ29hVgtbKUsnnXUGDKkisEPX8csGM9xKeVAdiYeFIRc6wt7RQwCd9bhk1C3Tz96sAy20UxrdJTGAOiCH+5NyB3WJCbugP+ervA5G5JCRuY6A7KjOqa/RYisE/FN4Fh0h6WAWdVpnuLFfhjeDFx4fUIEUsk0KhJxM8xyXaEg6WsIQ7fYk187AjfEDio5CCmRKkCKoBUfuP5UiDsyo0mIQhS5xv0f78VF6V7ELfcXkbjQHCkXjQrUz5rvREsb5rUhk71AcipCQu/JB2F1lL6O/68KX7G7en9zKrD3zq7YRig5HAAr9dRFDsLI/uDsDQ3S1QsKwQWun8YeT973SWSUBbNSzIWQ0U+bWrjR6LmHxlThGmSfPRSwiGU7TmSYmoVOZK0ob4FS8HTA+ev3kdecpK8HeGFvPcHZdXGDx8qikPos4G6CJMj1nqysptlajno7pgGeoP5RvwJjGdvmpXeKx7FrofA9tE/3HZi/hq4nCdD+CKNDIcaLgjF4/gVwawwnqmimZUOyM2R0soA8MJ9DRDgODrfnaeRyFn9I/sG/scApCbrnluCHKDVya36Y8nSrqgGL3ACo4B1wvgCkG6dZPNhwhAq68xiUw2HxCBeJ9K6RApV004rhhdP5GYsqBE2BwXpACN66O1Tf255KWaldFecFnpqvLB6yE0fJE/IiM8RbrZxWCM4CFi0LZV8GE4PYxjLeHRM9pc869eqieFPiRIgA7lF8f6EG9a0ATXCdq6SLZjrGhGKs+XRQayViWrWBt/rB/LN2ky6tiNjcYKlT7WQGAi/lfPo9+bfQa7eO/slxYgrikrSh3dvcWKomZ+OvsgZiI5xjW/nRidCEJmroGLWhrDIxmyGjjFe0lUNLX3hkcwFdmCzF7r+rsCtwWONqDMq0nP2bAl8SmylZ6vcWBUcDWFmjnCQ3bbeseD4TvJoZ/hweHobPqf/X1r4VlVa3gg1EhBsrSCCHpCBcKMSk45L70GNk895efOUCDXG+4JseADftc8QACT5Hj38eTuazLNuEz+RGRxmJIqCzzMnzflsKkd38CWLMz9Uk5dhO5i7A7E8DlTJPRrkpriAcLddcjAGRnIkk+YhWKiMpm6QcMlLRIAoX9cVHPmbOb1iuWQBJBAB0fWpuY5bP58ImCDx8RSgFZ58gJ8fiUkureeOOD5AO5rxEqplF5IACOXHdr9ujt1txJ02kKH5E/Tvc6U7CnEOYqSxq6xjVmpAjIJq9LDqSB1GS26G67qinXi52PqKLQYynpv7KLNX1oDXuF11E+E9jrtsSztPuYcFelPTF6d8P7yWLE7Mqq9T1000Fo4kiX+nPMfkRPfn3PQyQk+d0CQXOXrN4fCRjRzNkKl2H57emuVVrAcUeFO3afi5ExzRSItvivI9ttkZ1/vm7CvQo/+muBWB9MWoJ2yubHeznM30IG3/FInAEgz0k4GppVz1opF7nouSVzPxkkeMw/zu+JQQM0kGb4WLq+n6WsfdB/gv42VicY9WgMzwJpkuOeZ+MA4Zg670Z7gYJTCX5xmsKdFPQMbAB9f+pBYE/bgN6jV0Hg/mkv0PynwcGWrlWn6EmUTfFqWo3UdHPgO9lTAfqAwLtdG82iROMDVqSPAMXzgT1+hUtOTvwX5G3LlOJrdSuAMHKrMpZN9YPMTMopFT7Qbn/fKIhnoDRxi70IdBZw9QMgv5G3VgNJ+m3/1AoM8CkL+ZkhU9Wyz1A2JJ2cuTCMAy0aR2ke9dhtzW4LJ0L4vNtkrm4iTYIDLsSUE06xJ6mAGrnuhDOKAgKuEz4ht0AADtNZ0IoOGIStN0rBu7c8K4G

genericZkConfig.serverSecret: AMWhaRyvktoOYc8kkTAeb8urCwKtqiNnrpD3gcD9pn0BNWXwIAx/U6lRJSISUP0F4m+G4Pzrpk/WjyFMXbHuag+Up3cTD0zmVsTA9wPmfthbhwU1XseBLTlk+63MNQ3EWS8JYgbyWeSqFx0t+peN743xylkXyKxn6W5ltk1SKicIWLrf2ddW6MdBBtZUN1fO6wguwBIKxwNB6svSqEalsA2pklQF+otRhapkcQEKoI0zN/rq8yqklBYDrtGaKvTHB/pwontP+flig0cGCjOx11YwSe9JxKABRAdHzP7MVBEChwjuUzNBa1YWo3FbAyXRuQWYv6JwZzC87dkBzXplfwq6IZ/HGz3h2Vf+m++9nIGoIKeBv5MHxCUWeLctcp78C5F0BphW7DqtekJuZGfDDyF6rGxG4o47eQqI+WL+C5sCay60HjsqJCesqw9LqLbuDEbS1rdYSxOPtp6BbtISIAJjAx23PIF5mYAL/YRihaiXut4sYa5ziq6Bexe4HpuOCw==
callingZkConfig.serverSecret: AMWhaRyvktoOYc8kkTAeb8urCwKtqiNnrpD3gcD9pn0BNWXwIAx/U6lRJSISUP0F4m+G4Pzrpk/WjyFMXbHuag+Up3cTD0zmVsTA9wPmfthbhwU1XseBLTlk+63MNQ3EWS8JYgbyWeSqFx0t+peN743xylkXyKxn6W5ltk1SKicIWLrf2ddW6MdBBtZUN1fO6wguwBIKxwNB6svSqEalsA2pklQF+otRhapkcQEKoI0zN/rq8yqklBYDrtGaKvTHB/pwontP+flig0cGCjOx11YwSe9JxKABRAdHzP7MVBEChwjuUzNBa1YWo3FbAyXRuQWYv6JwZzC87dkBzXplfwq6IZ/HGz3h2Vf+m++9nIGoIKeBv5MHxCUWeLctcp78C5F0BphW7DqtekJuZGfDDyF6rGxG4o47eQqI+WL+C5sCay60HjsqJCesqw9LqLbuDEbS1rdYSxOPtp6BbtISIAJjAx23PIF5mYAL/YRihaiXut4sYa5ziq6Bexe4HpuOCw==
backupsZkConfig.serverSecret: AMWhaRyvktoOYc8kkTAeb8urCwKtqiNnrpD3gcD9pn0BNWXwIAx/U6lRJSISUP0F4m+G4Pzrpk/WjyFMXbHuag+Up3cTD0zmVsTA9wPmfthbhwU1XseBLTlk+63MNQ3EWS8JYgbyWeSqFx0t+peN743xylkXyKxn6W5ltk1SKicIWLrf2ddW6MdBBtZUN1fO6wguwBIKxwNB6svSqEalsA2pklQF+otRhapkcQEKoI0zN/rq8yqklBYDrtGaKvTHB/pwontP+flig0cGCjOx11YwSe9JxKABRAdHzP7MVBEChwjuUzNBa1YWo3FbAyXRuQWYv6JwZzC87dkBzXplfwq6IZ/HGz3h2Vf+m++9nIGoIKeBv5MHxCUWeLctcp78C5F0BphW7DqtekJuZGfDDyF6rGxG4o47eQqI+WL+C5sCay60HjsqJCesqw9LqLbuDEbS1rdYSxOPtp6BbtISIAJjAx23PIF5mYAL/YRihaiXut4sYa5ziq6Bexe4HpuOCw==

paymentsService.userAuthenticationTokenSharedSecret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA= # base64-encoded 32-byte secret shared with MobileCoin services used to generate auth tokens for Signal users
paymentsService.fixerApiKey: unset
paymentsService.coinGeckoApiKey: unset

currentReportingKey.secret: AAAAAAAAAAA=
currentReportingKey.salt: AAAAAAAAAAA=

registrationService.collationKeySalt: AAAAAAAAAAA=

turn.cloudflare.apiToken: ABCDEFGHIJKLM

linkDevice.secret: AAAAAAAAAAA=

tlsKeyStore.password: unset

noiseTunnel.tlsKeyStorePassword: flatline-test
noiseTunnel.noiseStaticPrivateKey: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
noiseTunnel.recognizedProxySecret: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789AAAAAAA
