name: Helm Test Images 

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]

jobs:
  helm:
    name: Helm Test Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1 
        with:
          version: v3.18.6

      - name: Install Python 
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up Chart Testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Create KinD Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      
      - name: Determine Container Image Tag
        id: tag
        run: |
          if [ "$GITHUB_REF_NAME" = "$DEFAULT_BRANCH" ]; then
            echo "tag=${DEFAULT_BRANCH}" >> $GITHUB_OUTPUT
            echo "extra-tags=latest" >> $GITHUB_OUTPUT
          else
            # Workflow only runs on the default branch and on PR branches.
            tag="pr-$(echo "$GITHUB_REF_NAME" | cut -d'/' -f1)"
            echo "tag=$tag" >> $GITHUB_OUTPUT
            echo "extra-tags=$tag" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          DEFAULT_BRANCH: ${{ env.DEFAULT_BRANCH }}

      - name: Chart Test Install
        run: |
          ct install \
          --helm-extra-args "--timeout 180s" \
          --helm-extra-set-args "--set=traefikResources.enabled=false" \
          --target-branch ${{ github.event.repository.default_branch }}
